### ISSUE TITLE
TODAY

### ISSUE THREAD

**Issue by AKuederle** [jcvasquezc/SMA2#89]
List of short fixes:

- [x] Fix #90 (Audioslider)
- [x] Fix #91 (Permissions)
- [x] Close #76 (Database persistens)
- [x] Close #88 (Database)
- [x] Next Button in settings leads to Login Page and not to main Menu #92 
- [x] Motivating message after each exercise should be added #102 
- [x] Check if language switching works correctly based on locals
- [x] Visual improvements for session overview #93
- [x] Fix #95 (App crashes)
- [x] Fix #97 (Profile Page Back button)
- [x] Improved spanish Translation (@PauPerezT )
- [x] If you press back in the main menu you get to the splash screen #110 
- [x] Fix button ovelap if screen is too small (@TAriasVergara )

Comment all things down below, what you thinks need to be done **today**! If we think it is doable, add it to the list

**Comment by AKuederle** [comment]
Check permissions? If the app doesn't have permissions it just chrashes after the first erxercise

**Comment by AKuederle** [comment]
Audio Slider does not seem to react to sound input @PKlumpp

**Comment by AKuederle** [comment]
App State is not persistent

**Comment by AKuederle** [comment]
Exercises restart even if session finsihed @AKuederle

**Comment by AKuederle** [comment]
Next Button in settings leads to Login Page and not to main Menu

**Comment by AKuederle** [comment]
Motivating message after each exercise should be added

**Comment by AKuederle** [comment]
Cleanup Exercises, that are not implemented in the new way

**Comment by AKuederle** [comment]
Reorder file structure for Layout files

**Comment by AKuederle** [comment]
Clean up general file structure

**Comment by AKuederle** [comment]
Rename everything to camel case

**Comment by AKuederle** [comment]
If you press back in the main menu you get to the splash screen
